export enum TflMode {
    bus = 'bus',
    cableCar = 'cable-car',
    coach = 'coach',
    cycle = 'cycle',
    cycleHire = 'cycle-hire',
    dlr = 'dlr',
    interchangeKeepSitting = 'interchange-keep-sitting',
    interchangeSecure = 'interchange-secure',
    nationalRail = 'national-rail',
    overground = 'overground',
    replacementBus = 'replacement-bus',
    riverBus = 'river-bus',
    riverTour = 'river-tour',
    taxi = 'taxi',
    tflrail = 'tflrail',
    tram = 'tram',
    tube = 'tube',
    walking = 'walking'
}
